import { motion } from 'framer-motion'
import { Check, Copy, RefreshCw } from 'lucide-react'
import { useState } from 'react'
import ReactMarkdown from 'react-markdown'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { oneLight } from 'react-syntax-highlighter/dist/esm/styles/prism'

function MessageBubble({ message, canRegenerate, onRegenerate }) {
  const [copied, setCopied] = useState(false)
  async function copyMessage() { await navigator.clipboard.writeText(message.content); setCopied(true); window.setTimeout(() => setCopied(false), 1400) }
  const time = new Intl.DateTimeFormat([], { hour: 'numeric', minute: '2-digit' }).format(new Date(message.createdAt))
  return <motion.article className={`designer-message ${message.role}`} initial={{ opacity: 0, y: 9 }} animate={{ opacity: 1, y: 0 }}>
    <div className="designer-bubble"><ReactMarkdown components={{ code({ className, children }) { const match = /language-(\w+)/.exec(className || ''); return match ? <SyntaxHighlighter style={oneLight} language={match[1]} PreTag="div">{String(children).replace(/\n$/, '')}</SyntaxHighlighter> : <code className={className}>{children}</code> } }}>{message.content}</ReactMarkdown>{message.type === 'image' && message.imageUrl && <img src={message.imageUrl} alt="Design reference generated by Haven" />}</div>
    <footer><time dateTime={message.createdAt}>{time}</time>{message.role === 'assistant' && <button onClick={copyMessage} aria-label="Copy response">{copied ? <Check size={13} /> : <Copy size={13} />}</button>}{canRegenerate && <button onClick={onRegenerate} aria-label="Regenerate response"><RefreshCw size={13} /></button>}</footer>
  </motion.article>
}
export default MessageBubble
